
services:
  database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123
    volumes:
      - sqldata:/var/opt/mssql/data

volumes:
  sqldata: